/* 

ESCREVA UMA FUNÇÃO QUE RECEBE UM NÚMERO E RETORNE O SEGUINTE:
NÚMERO É DIVISÍVEL POR 3 = FIZZ
NÚMERO É DIVISÍVEL POR 5 = BUZZ
NÚMERO É DIVISÍVEL POR 3 E 5 = FIZZBUZZ
NÚMERO NÃO É DIVISÍVEL POR 3 E 5 = RETORNA O PRÓPRIO NÚMERO
CHECAR SE O NÚMERO É REALMENTE UM NÚMERO
USE A FUNÇÃO COM NÚMEROS DE 0 A 100

*/