/* OPERADORES DE COMPARAÇÃO 

> MAIOR QUE
>= MAIOR OU IGUAL
< MENOR QUE
<= MENOR OU IGUAL
== IGUALDADE (VALOR)
=== IGUALDADE ESTRITA (VALOR E TIPO)
!= DIFERENTE (VALOR)
!== DIFERENTE ESTRITA (VALOR E TIPO)

*/